package com.autospace.app

import androidx.compose.runtime.compositionLocalOf

data class AppStrings(
    val commonExam: String,
    val commonLearning: String,
    val commonTestWord: String,
    val commonQuestionWord: String,
    val commonWakingHint: String,
    val commonSupport: String,
    val commonBack: String,

    val themeSwitchToLight: String,
    val themeSwitchToDark: String,

    val errorQuestionsNotFound: String,
    val errorServerSleeping: String,
    val errorServerUnreachablePrefix: String,

    val authLoginTitle: String,
    val authRegisterTitle: String,
    val authFirstName: String,
    val authLastName: String,
    val authEmail: String,
    val authUsername: String,
    val authPassword: String,
    val authShowPassword: String,
    val authHidePassword: String,
    val authLoginButton: String,
    val authRegisterButton: String,
    val authSwitchToRegister: String,
    val authSwitchToLogin: String,

    val pendingTitle: String,
    val pendingDescription: String,
    val pendingCheckStatus: String,
    val pendingNeedHelp: String,

    val supportScreenTitle: String,
    val supportScreenDescription: String,
    val supportKeepWaiting: String,
    val supportBackToRegistration: String,

    val blockedTitle: String,
    val blockedDescription: String,
    val blockedRegisterAgain: String,

    val supportFormMessage: String,
    val supportFormPhone: String,
    val supportFormEmail: String,
    val supportFormSentSuccess: String,
    val supportFormSend: String,

    val verifyTitle: String,
    val verifyDescription: (email: String) -> String,
    val verifyCodeLabel: String,
    val verifyConfirm: String,
    val verifyCodeProblem: String,
    val verifyResendInText: (seconds: Int) -> String,
    val verifyResendSending: String,
    val verifyResendLink: String,

    val mainMenuAppName: String,
    val mainMenuStats: String,
    val mainMenuResetAll: String,
    val mainMenuResetConfirmTitle: String,
    val mainMenuResetConfirmText: String,
    val mainMenuResetConfirmButton: String,
    val mainMenuResetting: String,
    val mainMenuCancel: String,
    val mainMenuAlreadyCompletedTitle: String,
    val mainMenuAlreadyCompletedText: (testLabel: String) -> String,
    val mainMenuOk: String,

    val statsTitle: String,
    val statsEmpty: String,
    val statsCompleted: String,
    val statsAccuracy: String,
    val statsBest: String,
    val statsDynamics: String,

    val testRetry: String,
    val testExplanation: String,
    val testPrev: String,
    val testNext: String,
    val testFinish: String,
    val testClose: String,
    val testFinishDialogTitle: String,
    val testFinishUnansweredText: (unanswered: Int, total: Int) -> String,
    val testFinishAllAnsweredText: String,
    val testContinue: String,
    val testFinishConfirm: String,

    val resultPerfect: String,
    val resultGood: String,
    val resultBad: String,
    val resultOutOf: (correct: Int, total: Int) -> String,
    val resultBackToMenu: String
)

val RussianStrings = AppStrings(
    commonExam = "Экзамен",
    commonLearning = "Обучение",
    commonTestWord = "Тест",
    commonQuestionWord = "Вопрос",
    commonWakingHint = "Подключение к серверу… Обычно это занимает до минуты",
    commonSupport = "Написать в поддержку",
    commonBack = "← Назад",

    themeSwitchToLight = "☀ Светлая тема",
    themeSwitchToDark = "🌙 Тёмная тема",

    errorQuestionsNotFound = "Вопросы для этого теста ещё не добавлены",
    errorServerSleeping = "Не удалось подключиться к серверу. Сервер мог «заснуть» — попробуйте ещё раз через минуту.",
    errorServerUnreachablePrefix = "Сервер недоступен",

    authLoginTitle = "Вход",
    authRegisterTitle = "Регистрация",
    authFirstName = "Имя",
    authLastName = "Фамилия",
    authEmail = "Почта",
    authUsername = "Логин",
    authPassword = "Пароль",
    authShowPassword = "Показать",
    authHidePassword = "Скрыть",
    authLoginButton = "Войти",
    authRegisterButton = "Зарегистрироваться",
    authSwitchToRegister = "Нет аккаунта? Зарегистрироваться",
    authSwitchToLogin = "Уже есть аккаунт? Войти",

    pendingTitle = "Ваша заявка обрабатывается",
    pendingDescription = "В течение 12 часов вы получите ответ",
    pendingCheckStatus = "Проверить статус",
    pendingNeedHelp = "Нужна помощь?",

    supportScreenTitle = "Поддержка",
    supportScreenDescription = "Если вы допустили ошибку при регистрации, вы можете начать заново. Либо продолжайте ожидать решение по вашей заявке.",
    supportKeepWaiting = "Продолжить ожидание",
    supportBackToRegistration = "Начать регистрацию заново",

    blockedTitle = "Доступ отклонён",
    blockedDescription = "К сожалению, ваша заявка была отклонена. Если считаете, что это ошибка, напишите нам.",
    blockedRegisterAgain = "Зарегистрироваться заново",

    supportFormMessage = "Сообщение",
    supportFormPhone = "Телефон (необязательно)",
    supportFormEmail = "Email (необязательно)",
    supportFormSentSuccess = "Сообщение отправлено!",
    supportFormSend = "Отправить",

    verifyTitle = "Подтверждение почты",
    verifyDescription = { email -> "Мы отправили код подтверждения на $email" },
    verifyCodeLabel = "Код из письма",
    verifyConfirm = "Подтвердить",
    verifyCodeProblem = "Код не приходит? Похоже, что-то пошло не так с доставкой письма",
    verifyResendInText = { s -> "Отправить код повторно можно через $s сек." },
    verifyResendSending = "Отправка...",
    verifyResendLink = "Не пришёл код? Отправить снова",

    mainMenuAppName = "Auto Space",
    mainMenuStats = "Статистика",
    mainMenuResetAll = "Обновить всё",
    mainMenuResetConfirmTitle = "Обновить всё?",
    mainMenuResetConfirmText = "Это удалит всю статистику и прогресс по всем тестам. Все тесты снова станут доступны для прохождения.",
    mainMenuResetConfirmButton = "Обновить",
    mainMenuResetting = "Обновление...",
    mainMenuCancel = "Отмена",
    mainMenuAlreadyCompletedTitle = "Тест уже пройден",
    mainMenuAlreadyCompletedText = { name -> "Вы уже прошли «$name». Чтобы пройти заново, нажмите «Обновить всё» внизу." },
    mainMenuOk = "Понятно",

    statsTitle = "Статистика",
    statsEmpty = "Вы пока не проходили тесты",
    statsCompleted = "Пройдено",
    statsAccuracy = "Успеваемость",
    statsBest = "Лучший",
    statsDynamics = "Динамика",

    testRetry = "Повторить",
    testExplanation = "Объяснение",
    testPrev = "← Пред.",
    testNext = "След. →",
    testFinish = "Завершить тест",
    testClose = "Закрыть",
    testFinishDialogTitle = "Завершить тест?",
    testFinishUnansweredText = { unanswered, total -> "Без ответа: $unanswered из $total. Нажмите на номер, чтобы перейти к вопросу." },
    testFinishAllAnsweredText = "Все вопросы отвечены. Нажмите на номер, чтобы вернуться к вопросу.",
    testContinue = "Продолжить",
    testFinishConfirm = "Завершить",

    resultPerfect = "Come on, go to pass the theory!",
    resultGood = "Сомнительно, ну окей!",
    resultBad = "Ещё нужно подучить!",
    resultOutOf = { correct, total -> "$correct из $total" },
    resultBackToMenu = "В меню"
)

val EnglishStrings = AppStrings(
    commonExam = "Exam",
    commonLearning = "Learning",
    commonTestWord = "Test",
    commonQuestionWord = "Question",
    commonWakingHint = "Connecting to server… This can take up to a minute",
    commonSupport = "Contact support",
    commonBack = "← Back",

    themeSwitchToLight = "☀ Light theme",
    themeSwitchToDark = "🌙 Dark theme",

    errorQuestionsNotFound = "Questions for this test haven't been added yet",
    errorServerSleeping = "Couldn't connect to the server. It may have gone to sleep — try again in a minute.",
    errorServerUnreachablePrefix = "Server unreachable",

    authLoginTitle = "Log in",
    authRegisterTitle = "Sign up",
    authFirstName = "First name",
    authLastName = "Last name",
    authEmail = "Email",
    authUsername = "Username",
    authPassword = "Password",
    authShowPassword = "Show",
    authHidePassword = "Hide",
    authLoginButton = "Log in",
    authRegisterButton = "Sign up",
    authSwitchToRegister = "No account? Sign up",
    authSwitchToLogin = "Already have an account? Log in",

    pendingTitle = "Your application is being processed",
    pendingDescription = "You'll get a response within 12 hours",
    pendingCheckStatus = "Check status",
    pendingNeedHelp = "Need help?",

    supportScreenTitle = "Support",
    supportScreenDescription = "If you made a mistake during registration, you can start over. Or keep waiting for a decision on your application.",
    supportKeepWaiting = "Keep waiting",
    supportBackToRegistration = "Start registration over",

    blockedTitle = "Access denied",
    blockedDescription = "Unfortunately, your application was rejected. If you think this is a mistake, contact us.",
    blockedRegisterAgain = "Register again",

    supportFormMessage = "Message",
    supportFormPhone = "Phone (optional)",
    supportFormEmail = "Email (optional)",
    supportFormSentSuccess = "Message sent!",
    supportFormSend = "Send",

    verifyTitle = "Confirm your email",
    verifyDescription = { email -> "We've sent a verification code to $email" },
    verifyCodeLabel = "Code from the email",
    verifyConfirm = "Confirm",
    verifyCodeProblem = "Code not arriving? Something may have gone wrong with delivery",
    verifyResendInText = { s -> "You can resend the code in ${s}s" },
    verifyResendSending = "Sending...",
    verifyResendLink = "Code didn't arrive? Resend it",

    mainMenuAppName = "Auto Space",
    mainMenuStats = "Statistics",
    mainMenuResetAll = "Reset all",
    mainMenuResetConfirmTitle = "Reset all?",
    mainMenuResetConfirmText = "This will delete all statistics and progress across all tests. All tests will become available again.",
    mainMenuResetConfirmButton = "Reset",
    mainMenuResetting = "Resetting...",
    mainMenuCancel = "Cancel",
    mainMenuAlreadyCompletedTitle = "Test already completed",
    mainMenuAlreadyCompletedText = { name -> "You've already completed \u00ab$name\u00bb. To retake it, tap \u00abReset all\u00bb below." },
    mainMenuOk = "Got it",

    statsTitle = "Statistics",
    statsEmpty = "You haven't taken any tests yet",
    statsCompleted = "Completed",
    statsAccuracy = "Accuracy",
    statsBest = "Best",
    statsDynamics = "Progress",

    testRetry = "Retry",
    testExplanation = "Explanation",
    testPrev = "← Prev",
    testNext = "Next →",
    testFinish = "Finish test",
    testClose = "Close",
    testFinishDialogTitle = "Finish the test?",
    testFinishUnansweredText = { unanswered, total -> "Unanswered: $unanswered of $total. Tap a number to jump to that question." },
    testFinishAllAnsweredText = "All questions answered. Tap a number to go back to it.",
    testContinue = "Continue",
    testFinishConfirm = "Finish",

    resultPerfect = "Come on, go to pass the theory!",
    resultGood = "Iffy, but okay!",
    resultBad = "You still need to study more!",
    resultOutOf = { correct, total -> "$correct out of $total" },
    resultBackToMenu = "Back to menu"
)

val SpanishStrings = AppStrings(
    commonExam = "Examen",
    commonLearning = "Aprendizaje",
    commonTestWord = "Test",
    commonQuestionWord = "Pregunta",
    commonWakingHint = "Conectando con el servidor… Puede tardar hasta un minuto",
    commonSupport = "Escribir a soporte",
    commonBack = "← Atrás",

    themeSwitchToLight = "☀ Tema claro",
    themeSwitchToDark = "🌙 Tema oscuro",

    errorQuestionsNotFound = "Las preguntas de este test todavía no se han añadido",
    errorServerSleeping = "No se pudo conectar con el servidor. Puede que se haya \"dormido\" — inténtalo de nuevo en un minuto.",
    errorServerUnreachablePrefix = "Servidor no disponible",

    authLoginTitle = "Iniciar sesión",
    authRegisterTitle = "Registrarse",
    authFirstName = "Nombre",
    authLastName = "Apellido",
    authEmail = "Correo",
    authUsername = "Usuario",
    authPassword = "Contraseña",
    authShowPassword = "Mostrar",
    authHidePassword = "Ocultar",
    authLoginButton = "Iniciar sesión",
    authRegisterButton = "Registrarse",
    authSwitchToRegister = "¿No tienes cuenta? Regístrate",
    authSwitchToLogin = "¿Ya tienes cuenta? Inicia sesión",

    pendingTitle = "Tu solicitud está siendo procesada",
    pendingDescription = "Recibirás una respuesta en un plazo de 12 horas",
    pendingCheckStatus = "Comprobar estado",
    pendingNeedHelp = "¿Necesitas ayuda?",

    supportScreenTitle = "Soporte",
    supportScreenDescription = "Si cometiste un error al registrarte, puedes empezar de nuevo. O sigue esperando una decisión sobre tu solicitud.",
    supportKeepWaiting = "Seguir esperando",
    supportBackToRegistration = "Empezar el registro de nuevo",

    blockedTitle = "Acceso denegado",
    blockedDescription = "Lamentablemente, tu solicitud fue rechazada. Si crees que es un error, escríbenos.",
    blockedRegisterAgain = "Registrarse de nuevo",

    supportFormMessage = "Mensaje",
    supportFormPhone = "Teléfono (opcional)",
    supportFormEmail = "Email (opcional)",
    supportFormSentSuccess = "¡Mensaje enviado!",
    supportFormSend = "Enviar",

    verifyTitle = "Confirmación de correo",
    verifyDescription = { email -> "Hemos enviado un código de confirmación a $email" },
    verifyCodeLabel = "Código del correo",
    verifyConfirm = "Confirmar",
    verifyCodeProblem = "¿El código no llega? Parece que algo falló con la entrega",
    verifyResendInText = { s -> "Podrás reenviar el código en $s s" },
    verifyResendSending = "Enviando...",
    verifyResendLink = "¿No llegó el código? Reenviar",

    mainMenuAppName = "Auto Space",
    mainMenuStats = "Estadísticas",
    mainMenuResetAll = "Restablecer todo",
    mainMenuResetConfirmTitle = "¿Restablecer todo?",
    mainMenuResetConfirmText = "Esto eliminará todas las estadísticas y el progreso de todos los tests. Todos los tests volverán a estar disponibles.",
    mainMenuResetConfirmButton = "Restablecer",
    mainMenuResetting = "Restableciendo...",
    mainMenuCancel = "Cancelar",
    mainMenuAlreadyCompletedTitle = "Test ya realizado",
    mainMenuAlreadyCompletedText = { name -> "Ya has completado «$name». Para repetirlo, pulsa «Restablecer todo» abajo." },
    mainMenuOk = "Entendido",

    statsTitle = "Estadísticas",
    statsEmpty = "Todavía no has hecho ningún test",
    statsCompleted = "Completados",
    statsAccuracy = "Aciertos",
    statsBest = "Mejor resultado",
    statsDynamics = "Evolución",

    testRetry = "Reintentar",
    testExplanation = "Explicación",
    testPrev = "← Ant.",
    testNext = "Sig. →",
    testFinish = "Finalizar test",
    testClose = "Cerrar",
    testFinishDialogTitle = "¿Finalizar el test?",
    testFinishUnansweredText = { unanswered, total -> "Sin responder: $unanswered de $total. Toca un número para ir a esa pregunta." },
    testFinishAllAnsweredText = "Todas las preguntas están respondidas. Toca un número para volver a ella.",
    testContinue = "Continuar",
    testFinishConfirm = "Finalizar",

    resultPerfect = "Come on, go to pass the theory!",
    resultGood = "Dudoso, ¡pero vale!",
    resultBad = "¡Todavía tienes que estudiar más!",
    resultOutOf = { correct, total -> "$correct de $total" },
    resultBackToMenu = "Al menú"
)

val GermanStrings = AppStrings(
    commonExam = "Prüfung",
    commonLearning = "Lernen",
    commonTestWord = "Test",
    commonQuestionWord = "Frage",
    commonWakingHint = "Verbindung zum Server… Das kann bis zu einer Minute dauern",
    commonSupport = "An den Support schreiben",
    commonBack = "← Zurück",

    themeSwitchToLight = "☀ Helles Design",
    themeSwitchToDark = "🌙 Dunkles Design",

    errorQuestionsNotFound = "Die Fragen für diesen Test wurden noch nicht hinzugefügt",
    errorServerSleeping = "Verbindung zum Server fehlgeschlagen. Er könnte „eingeschlafen“ sein — versuchen Sie es in einer Minute erneut.",
    errorServerUnreachablePrefix = "Server nicht erreichbar",

    authLoginTitle = "Anmelden",
    authRegisterTitle = "Registrieren",
    authFirstName = "Vorname",
    authLastName = "Nachname",
    authEmail = "E-Mail",
    authUsername = "Benutzername",
    authPassword = "Passwort",
    authShowPassword = "Anzeigen",
    authHidePassword = "Verbergen",
    authLoginButton = "Anmelden",
    authRegisterButton = "Registrieren",
    authSwitchToRegister = "Kein Konto? Registrieren",
    authSwitchToLogin = "Schon ein Konto? Anmelden",

    pendingTitle = "Ihr Antrag wird bearbeitet",
    pendingDescription = "Sie erhalten innerhalb von 12 Stunden eine Antwort",
    pendingCheckStatus = "Status prüfen",
    pendingNeedHelp = "Brauchen Sie Hilfe?",

    supportScreenTitle = "Support",
    supportScreenDescription = "Wenn Sie sich bei der Registrierung geirrt haben, können Sie neu beginnen. Oder warten Sie weiter auf eine Entscheidung zu Ihrem Antrag.",
    supportKeepWaiting = "Weiter warten",
    supportBackToRegistration = "Registrierung neu starten",

    blockedTitle = "Zugang verweigert",
    blockedDescription = "Leider wurde Ihr Antrag abgelehnt. Wenn Sie glauben, dass dies ein Fehler ist, schreiben Sie uns.",
    blockedRegisterAgain = "Erneut registrieren",

    supportFormMessage = "Nachricht",
    supportFormPhone = "Telefon (optional)",
    supportFormEmail = "E-Mail (optional)",
    supportFormSentSuccess = "Nachricht gesendet!",
    supportFormSend = "Senden",

    verifyTitle = "E-Mail-Bestätigung",
    verifyDescription = { email -> "Wir haben einen Bestätigungscode an $email gesendet" },
    verifyCodeLabel = "Code aus der E-Mail",
    verifyConfirm = "Bestätigen",
    verifyCodeProblem = "Code kommt nicht an? Bei der Zustellung ist wohl etwas schiefgelaufen",
    verifyResendInText = { s -> "Erneutes Senden ist in ${s}s möglich" },
    verifyResendSending = "Wird gesendet...",
    verifyResendLink = "Code nicht angekommen? Erneut senden",

    mainMenuAppName = "Auto Space",
    mainMenuStats = "Statistik",
    mainMenuResetAll = "Alles zurücksetzen",
    mainMenuResetConfirmTitle = "Alles zurücksetzen?",
    mainMenuResetConfirmText = "Dies löscht alle Statistiken und den Fortschritt aller Tests. Alle Tests stehen danach wieder zur Verfügung.",
    mainMenuResetConfirmButton = "Zurücksetzen",
    mainMenuResetting = "Wird zurückgesetzt...",
    mainMenuCancel = "Abbrechen",
    mainMenuAlreadyCompletedTitle = "Test bereits abgeschlossen",
    mainMenuAlreadyCompletedText = { name -> "Sie haben «$name» bereits abgeschlossen. Um ihn zu wiederholen, tippen Sie unten auf «Alles zurücksetzen»." },
    mainMenuOk = "Verstanden",

    statsTitle = "Statistik",
    statsEmpty = "Sie haben noch keine Tests absolviert",
    statsCompleted = "Abgeschlossen",
    statsAccuracy = "Erfolgsquote",
    statsBest = "Bestes Ergebnis",
    statsDynamics = "Verlauf",

    testRetry = "Wiederholen",
    testExplanation = "Erklärung",
    testPrev = "← Zurück",
    testNext = "Weiter →",
    testFinish = "Test beenden",
    testClose = "Schließen",
    testFinishDialogTitle = "Test beenden?",
    testFinishUnansweredText = { unanswered, total -> "Unbeantwortet: $unanswered von $total. Tippen Sie auf eine Zahl, um zur Frage zu springen." },
    testFinishAllAnsweredText = "Alle Fragen wurden beantwortet. Tippen Sie auf eine Zahl, um zurückzukehren.",
    testContinue = "Weiter",
    testFinishConfirm = "Beenden",

    resultPerfect = "Come on, go to pass the theory!",
    resultGood = "Fraglich, aber okay!",
    resultBad = "Sie müssen noch üben!",
    resultOutOf = { correct, total -> "$correct von $total" },
    resultBackToMenu = "Zum Menü"
)

val UkrainianStrings = AppStrings(
    commonExam = "Іспит",
    commonLearning = "Навчання",
    commonTestWord = "Тест",
    commonQuestionWord = "Питання",
    commonWakingHint = "Підключення до сервера… Зазвичай це займає до хвилини",
    commonSupport = "Написати в підтримку",
    commonBack = "← Назад",

    themeSwitchToLight = "☀ Світла тема",
    themeSwitchToDark = "🌙 Темна тема",

    errorQuestionsNotFound = "Питання для цього тесту ще не додано",
    errorServerSleeping = "Не вдалося підключитися до сервера. Сервер міг «заснути» — спробуйте ще раз через хвилину.",
    errorServerUnreachablePrefix = "Сервер недоступний",

    authLoginTitle = "Вхід",
    authRegisterTitle = "Реєстрація",
    authFirstName = "Ім'я",
    authLastName = "Прізвище",
    authEmail = "Пошта",
    authUsername = "Логін",
    authPassword = "Пароль",
    authShowPassword = "Показати",
    authHidePassword = "Приховати",
    authLoginButton = "Увійти",
    authRegisterButton = "Зареєструватися",
    authSwitchToRegister = "Немає акаунта? Зареєструватися",
    authSwitchToLogin = "Вже є акаунт? Увійти",

    pendingTitle = "Вашу заявку опрацьовують",
    pendingDescription = "Протягом 12 годин ви отримаєте відповідь",
    pendingCheckStatus = "Перевірити статус",
    pendingNeedHelp = "Потрібна допомога?",

    supportScreenTitle = "Підтримка",
    supportScreenDescription = "Якщо ви припустилися помилки під час реєстрації, можете почати заново. Або продовжуйте очікувати рішення щодо вашої заявки.",
    supportKeepWaiting = "Продовжити очікування",
    supportBackToRegistration = "Почати реєстрацію заново",

    blockedTitle = "Доступ відхилено",
    blockedDescription = "На жаль, вашу заявку було відхилено. Якщо вважаєте, що це помилка, напишіть нам.",
    blockedRegisterAgain = "Зареєструватися знову",

    supportFormMessage = "Повідомлення",
    supportFormPhone = "Телефон (необов'язково)",
    supportFormEmail = "Email (необов'язково)",
    supportFormSentSuccess = "Повідомлення надіслано!",
    supportFormSend = "Надіслати",

    verifyTitle = "Підтвердження пошти",
    verifyDescription = { email -> "Ми надіслали код підтвердження на $email" },
    verifyCodeLabel = "Код із листа",
    verifyConfirm = "Підтвердити",
    verifyCodeProblem = "Код не приходить? Схоже, щось пішло не так з доставкою листа",
    verifyResendInText = { s -> "Повторно надіслати код можна через $s с." },
    verifyResendSending = "Надсилання...",
    verifyResendLink = "Не прийшов код? Надіслати знову",

    mainMenuAppName = "Auto Space",
    mainMenuStats = "Статистика",
    mainMenuResetAll = "Оновити все",
    mainMenuResetConfirmTitle = "Оновити все?",
    mainMenuResetConfirmText = "Це видалить всю статистику та прогрес за всіма тестами. Усі тести знову стануть доступні для проходження.",
    mainMenuResetConfirmButton = "Оновити",
    mainMenuResetting = "Оновлення...",
    mainMenuCancel = "Скасувати",
    mainMenuAlreadyCompletedTitle = "Тест уже пройдено",
    mainMenuAlreadyCompletedText = { name -> "Ви вже пройшли «$name». Щоб пройти знову, натисніть «Оновити все» внизу." },
    mainMenuOk = "Зрозуміло",

    statsTitle = "Статистика",
    statsEmpty = "Ви ще не проходили тести",
    statsCompleted = "Пройдено",
    statsAccuracy = "Успішність",
    statsBest = "Найкращий",
    statsDynamics = "Динаміка",

    testRetry = "Повторити",
    testExplanation = "Пояснення",
    testPrev = "← Попер.",
    testNext = "Далі →",
    testFinish = "Завершити тест",
    testClose = "Закрити",
    testFinishDialogTitle = "Завершити тест?",
    testFinishUnansweredText = { unanswered, total -> "Без відповіді: $unanswered із $total. Натисніть на номер, щоб перейти до питання." },
    testFinishAllAnsweredText = "На всі питання дано відповідь. Натисніть на номер, щоб повернутися до нього.",
    testContinue = "Продовжити",
    testFinishConfirm = "Завершити",

    resultPerfect = "Come on, go to pass the theory!",
    resultGood = "Сумнівно, ну гаразд!",
    resultBad = "Ще потрібно підучити!",
    resultOutOf = { correct, total -> "$correct із $total" },
    resultBackToMenu = "У меню"
)

fun stringsFor(language: Language): AppStrings {
    return when (language) {
        Language.RUSSIAN -> RussianStrings
        Language.ENGLISH -> EnglishStrings
        Language.SPANISH -> SpanishStrings
        Language.GERMAN -> GermanStrings
        Language.UKRAINIAN -> UkrainianStrings
    }
}

val LocalStrings = compositionLocalOf { RussianStrings }